### ISSUE TITLE
transaction object doesn't have sub-objects in golang

### ISSUE THREAD

**Issue by ssinger** [unit-finance/openapi-unit-sdk#23]
If I generate a golang client I get the following

~~~
type Transaction struct {
        Id *string `json:"id,omitempty"`
        Type *string `json:"type,omitempty"`
}
~~~

in model_transaction.go

I think it should have sub-objects for each of the different transaction types.

I see this with both openapi-generator and the swagger-cli-3.0.36

**Comment by Yaellever** [comment]
@ssinger  As far as we can tell, Transactions is built in the same way as the other objects. Can you please share the response you get to a LIST transactions request? Also, have you been able to use the go-SDK successfully with other objects? for example the different types of applications
@axshani

**Comment by ssinger** [comment]
I haven't yet been able to use the generated golang openapi client.  I am replacing an in-house generated client with one generated from here (or trying to) but I can't easily run the application until I replace all the api calls we use.

For the transaction object I think https://github.com/unit-finance/openapi-unit-sdk/pull/25 is closer to what you want.  I think other object types have the same issue.   I tried generating clients in golang, java and typescript from the main branch and none of them seem to have the subtypes accessible in the Transaction list.

**Comment by axshani** [comment]
Hey!, first of all thank you for the feedback and the great input.

When I'm using the generated Java-SDK, it generates a JSON.java file with all of the discriminator types

for example:
![image](https://github.com/unit-finance/openapi-unit-sdk/assets/77099403/fcec934c-8864-48ef-8f14-da7c0bbe03b5)

this is why I believed that in Golang the generator will do the same. I will try also your suggestion about `oneOf` 
thanks

**Comment by ssinger** [comment]
~~~
java -jar /usr/local/bin/openapi-generator-cli-6.2.1.jar generate -o generated_javat -i openapi.json -g java
~~~


gives me
 generated_javat/src/main/java/org/openapitools/client/model/Transaction.java

~~~
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-06-26T11:12:58.414179-04:00[America/Toronto]")
public class Transaction {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  protected String type;


~~~

**Comment by ssinger** [comment]
To be clear, the java file generated above has the subtypes in  validateJsonObject
but they aren't generated as attributes of the class so I don't see how one would be able to use the dataafields

**Comment by axshani** [comment]
You don't need to use Transaction class, for example the method GetListTransactions will return a list of defferent kinds of transactions and each class has his own attributes. If you can maybe add an example of your usage it will be great :)

**Comment by ssinger** [comment]
I'm using the golang client not the java client, I'm mostly mentioning Java just to make sure it isn't an issue specific to the golang generator.

The Java GetListTransactions method generated is as follows

~~~
 /**
     * Get List Transactions
     * Get List Transactions from API
     * @param page  (optional)
     * @param filter  (optional)
     * @param sort  (optional, default to -createdAt)
     * @return List&lt;Transaction&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful Response </td><td>  -  </td></tr>
     </table>
     */
    public List<Transaction> execute(ListPageParametersObject page, ExecuteFilterParameter filter, String sort) throws ApiException {
        ApiResponse<List<Transaction>> localVarResp = executeWithHttpInfo(page, filter, sort);
        return localVarResp.getData();

~~~
from src/main/java/org/openapitools/client/api/GetListTransactionsApi.java

it returns a List<Transaction> object.

**Comment by axshani** [comment]
https://github.com/unit-finance/openapi-unit-sdk/pull/25

Merged. thanks.
